name: 'Terraform Azure Provisioning'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Create directory
      run: mkdir -p /home/runner/work/terraform/terraform/terraform
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: List contents of /home/runner
      run: ls -la /home/runner  
      
    - name: List contents of working directory
      run: ls -la /home/runner/work/terraform/terraform/.git/
      
    - name: Check backend configuration
      run: cat /home/runner/work/terraform/terraform/./terraform/main.tf
      
    - name: Authenticate Azure
      run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Terraform init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
